# Generated by Django 5.2.16 on 2026-07-29 12:34

import apps.qr_tracking.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('otp', models.CharField(default=apps.qr_tracking.models.generate_otp, max_length=6)),
                ('expires_at', models.DateTimeField(default=apps.qr_tracking.models.default_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover_token_record', to='claims.claim')),
            ],
        ),
    ]
