# Generated by Django 5.2.16 on 2026-07-29 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=80)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('event_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/%Y/%m/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLAIMED', 'Claim in Progress'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'status'], name='items_item_report__c85be0_idx'), models.Index(fields=['category'], name='items_item_categor_db7f55_idx'), models.Index(fields=['event_date'], name='items_item_event_d_76811f_idx')],
            },
        ),
    ]
